env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - react
rules:
  indent: ["error", 2]
  react/jsx-indent: ["error", 2]
  react/jsx-indent-props: ["error", 2]
  "@typescript-eslint/indent": ["error", 2]
settings:
  react:
    version: "detect"

